language: node_js
node_js: 6.2.0
branches:
  only:
    - master
install:
  - npm install
  - git config user.name "Travis CI"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
before_script:
  - rm -rf dist
  - git clone -b gh-pages https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} dist
  - cd dist && git checkout gh-pages
script:
  - npm build
after_success:
  - cd dist &&
    git add . &&
    git ci -m'Travis build for ${TRAVIS_COMMIT}' &&
    git push --force
