# This requires a GH_TOKEN env var in your Travis-CI project settings,
# generated here: https://github.com/settings/tokens
language: node_js
node_js: 6.2.0
branches:
  only:
    - master
install:
  - npm install
  - git config --global user.name "Travis CI" &&
  - git config --global user.email "$COMMIT_AUTHOR_EMAIL" &&
before_script:
  - git clone --depth 10 --branch gh-pages https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} /home/travis/build/${TRAVIS_REPO_SLUG}/dist
script:
  - npm run build
after_success:
  - cd /home/travis/build/${TRAVIS_REPO_SLUG}/dist &&
    git add . &&
    git commit -m'Travis build for ${TRAVIS_COMMIT}' &&
    git push --force
